openapi: 3.0.0
info:
  title: API Artistas
  description: API para gerenciar informações de artistas
  version: 1.0.0

servers:
  - url: "https://localhost:3000"

tags:
  - name: User
    description: Operações relacionadas a usuários

  - name: artistas
    description: Operações relacionadas a artistas

  - name: Songs
    description: Operações relacionadas a músicas

  - name: Albums
    description: Operações relacionadas a álbuns

  - name: Admin
    description: Operações administrativas

paths:
  # rota
  /user/register:
    # metodo
    post:
      # titulo
      summary: "Cadastro de usuário"
      # descricao
      description: "Cria um novo usuário no sistema"
      tags:
        - User

        # corpo da requisição
      requestBody:
        # tipo de conteudo
        content:
          application/json:
            # esquema de dados
            schema:
              $ref: "#/components/schemas/UserRegister"
              # exemplo de dados
            examples:
              User:
                summary: "Exemplo de usuário"
                value:
                  name: "João Silva"
                  email: "joao.silva@example.com"
                  password: "senha123"
      # resposta
      responses:
        "400":
          description: "Erro ao criar usuário"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"

                example:
                  message: "Erro ao criar usuário"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
        "201":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegister"

  /user/all:
    get:
      summary: "Listar todos os usuários"
      description: "Retorna uma lista de todos os usuários cadastrados"
      tags:
        - User
      security:
        - bearerAuth: []

      responses:
        "200":
          description: "Lista de usuários"
          content:
           application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/UserRegister"

            example:
              User:

                value: 
                  - id: 1
                    name: "João Silva"
                    email: "joao.silva@example.com"
                    password: "hashedPassword"

                  - id: 2
                    name: "Roberto Souza"
                    email: "roberto.souza@example.com"
                    password: "hashedPassword"

                  - id: 3
                    name: "Maria Oliveira"
                    email: "maria.oliveira@example.com"
                    password: "hashedPassword"
        '500':
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"

                example:
                  message: "Erro interno do servidor"             

  /user/login:
    post:
      summary: "Login de usuário"
      description: "Realiza o login de um usuário no sistema"
      tags:
        - User
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"
              examples:
                User:
                  summary: "Exemplo de usuário"
                  value:
                    email: "joao.silva@example.com"
                    password: "hashedPassword"

      responses:
        "404":
          description: "Usuário não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Usuário não encontrado"


        "400":
          description: "Erro ao realizar login"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Email ou senha inválidos"

        "200":
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "Token de autenticação do usuário"

              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
  /user/delete/{id}:
    delete:
      summary: "Deletar usuário"
      tags:
        - User
      description: "Deleta um usuário do sistema"
      parameters:
        - name: id
          in: path
          description: "ID do usuário a ser deletado"
          required: true
          schema:
            type: string
            
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Usuário deletado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Deletado com sucesso"
                example:
                  message: "Usuário deletado com sucesso"
        "404":
          description: "Usuário não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Usuário não encontrado"
                example:
                  message: "Usuário não encontrado"
          
        "400":
          description: "ID inválido"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "ID inválido"
                example:
                  message: "ID inválido"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /admin/register:
    post:
      tags:
        - Admin
      summary: "Cadastro de administrador"
      description: "Cria um novo administrador no sistema"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserRegister"
      responses:
        "200":
          description: "Administrador criado com sucesso"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRegister"
              examples:
                Admin:
                  summary: "Exemplo de administrador criado"
                  value:
                    name: "Admin"
                    email: "admin@example.com"
                    password: "admin123"

        "400":
          description: "Email inválido ou senha muito curta"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Email inválido ou senha muito curta"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"  


  /admin/login:
    post:
      tags:
        - Admin
      summary: "Login de administrador"
      description: "Realiza o login de um administrador no sistema"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UserLogin"

      responses:
        "200":
          description: "Login bem-sucedido"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: "Token de autenticação do administrador"
              example:
                token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."

        "400":
          description: "Email ou senha inválidos"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Email ou senha inválidos"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"     

        "404":
          description: "Administrador não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Administrador não encontrado" 

  /artist/create:
    post:
      tags:
        - artistas
      summary: "Cadastro de artista"
      description: "Cria um novo artista no sistema"
      security:
        - bearerAuth: []
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArtistCreate"
      responses:
        "200":
          description: "Artista criado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "ID do artista"
                  name:
                    type: string
                    description: "Nome do artista"
                  genre:
                    type: string
                    description: "Gênero musical do artista"
                  bio:
                    type: string
                    description: "Biografia do artista"
                  imageURL:
                    type: string
                    description: "URL da imagem do artista"
              example:
                id: 1
                name: "Artista Exemplo"
                genre: "Pop"
                bio: "Biografia do artista exemplo."
                imageURL: "https://example.com/image.jpg"

        "400":
          description: "Erro ao criar artista"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Todos os campos são obrigatórios"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /artist/all:
    get:
      tags:
        - artistas
      security:
         - bearerAuth: []
        
      summary: "Listar todos os artistas"
      description: "Retorna uma lista de todos os artistas cadastrados"
      responses:
        "200":
          description: "Lista de artistas"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ArtistCreate"
              example:
                - id: 1
                  name: "Artista Exemplo"
                  genre: "Pop"
                  bio: "Biografia do artista exemplo."
                  imageURL: "https://example.com/image.jpg"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"  

  /artist/update/{id}:
    put:
      tags:
        - artistas
      summary: "Atualizar artista"
      description: "Atualiza as informações de um artista existente"
      parameters:
        - name: id
          in: path
          description: "ID do artista a ser atualizado"
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ArtistCreate"

      security:
        - bearerAuth: []

      responses:
        "200":
          description: "Artista atualizado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de sucesso"
                example:
                  message: "Artista atualizado com sucesso"

        "404":
          description: "Artista não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Artista não encontrado"

        "400":
          description: "ID é obrigatório"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "ID é obrigatório"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
                


  /artist/delete/{id}:
    delete:
      tags:
        - artistas
      summary: "Deletar artista"
      description: "Deleta um artista do sistema"
      parameters:
        - name: id
          in: path
          description: "ID do artista a ser deletado"
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Artista deletado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Deletado com sucesso"
                example:
                  message: "Artista deletado com sucesso"
        "404":
          description: "Artista não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Artista não encontrado"

        "400":
          description: "ID inválido" 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "ID inválido"
                example:
                  message: "ID inválido"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

                  
  /artist/songs/create:
    post:
      tags:
        - Songs
      summary: "Cria musicas para um artista"
      description: "Cria uma música para o sistema"
      security:
        - bearerAuth: []
      
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SongsCreate"
      responses:
        "201":
          description: "Música criada com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: "ID da música"
                  title:
                    type: string
                    description: "Título da música"
                  duration:
                    type: string
                    description: "Duração da música"
                  artistName:
                    type: string
                    description: "Nome do artista"
                  imageURL:
                    type: string
                    description: "URL da imagem da música"
              example:
                id: 1
                title: "Música Exemplo"
                duration: "3:45"
                artistName: "Artista Exemplo"
                imageURL: "https://example.com/image.jpg"

        "400":
          description: "Erro ao criar música"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Todos os campos são obrigatórios"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

        "404":
            description: "Artista não encontrado"
            content:
              application/json:
                  schema:
                    type: object
                    properties:
                      message:
                        type: string
                        description: "Mensagem de erro"
                        example:
                            message: "Artista não encontrado"

  /artist/songs/all:
    get:
      tags:
        - Songs
      security:
        - bearerAuth: []

      summary: "Listar todas as músicas"
      description: "Retorna uma lista de todas as músicas cadastradas"
      responses:
        "200":
          description: "Lista de músicas"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SongsCreate"
              example:
                - id: 1
                  title: "Música Exemplo"
                  duration: "3:45"
                  artistName: "Artista Exemplo"
                  imageURL: "https://example.com/image.jpg"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /artist/songs/update/{id}:
    put:
      tags:
        - Songs
      summary: "Atualizar música"
      description: "Atualiza as informações de uma música existente"
      parameters:
        - name: id
          in: path
          description: "ID da música a ser atualizada"
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SongsCreate"

      security:
        - bearerAuth: []

      responses:
        "200":
          description: "Música atualizada com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de sucesso"
                example:
                  message: "Música atualizada com sucesso"

        "404":
          description: "Música não encontrada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Música não encontrada"

        "400":
          description: "ID é obrigatório"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "ID é obrigatório"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
                  
  /artist/songs/delete/{id}:
    delete:
      tags:
        - Songs
      summary: "Deletar música"
      description: "Deleta uma música do sistema"
      parameters:
        - name: id
          in: path
          description: "ID da música a ser deletada"
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Música deletada com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Deletado com sucesso"
                example:
                  message: "Música deletada com sucesso"
        "404":
          description: "Música não encontrada"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Música não encontrada"

        "400":
          description: "ID inválido" 
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "ID inválido"
                example:
                  message: "ID inválido"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /artist/albums/create:
    post:
      tags:
        - Albums
      summary: "Criar álbum"
      description: "Cria um novo álbum no sistema"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlbumCreate"
      security:
        - bearerAuth: []
      responses:
        "201":
          description: "Álbum criado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Álbum criado com sucesso"
                example:
                  message: "Álbum criado com sucesso"
        "404":
          description: "Artista não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Artista não encontrado"          
        "400":
          description: "Dados inválidos"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Dados inválidos"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
  /artist/albums/all:
    get:
      tags:
        - Albums
      security:
        - bearerAuth: []
      
      summary: "Listar todos os álbuns"
      description: "Retorna uma lista de todos os álbuns cadastrados"
      responses:
        "200":
          description: "Lista de álbuns"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AlbumCreate"
              example:
                - id: 1
                  title: "Álbum Exemplo"
                  artistName: "Artista Exemplo"
                  releaseDate: "2023-10-01T00:00:00Z"
                  imageURL: "https://example.com/album.jpg"
                  imageBase64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."       

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"

  /artist/albums/update/{id}:
    put:
      tags:
        - Albums
      summary: "Atualizar álbum"
      description: "Atualiza as informações de um álbum existente"
      parameters:
        - name: id
          in: path
          description: "ID do álbum a ser atualizado"
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AlbumCreate"

      security:
        - bearerAuth: []

      responses:
        "200":
          description: "Álbum atualizado com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de sucesso"
                example:
                  message: "Álbum atualizado com sucesso"

        "404":
          description: "Álbum não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Álbum não encontrado"

        "400":
          description: "ID é obrigatório"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "ID é obrigatório"

        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
  /artist/albums/delete/{id}:
    delete:
      tags:
        - Albums
      summary: "Deletar álbum"
      description: "Remove um álbum existente"
      parameters:
        - name: id
          in: path
          description: "ID do álbum a ser removido"
          required: true
          schema:
            type: string
      security:
        - bearerAuth: []
      responses:
        "200":
          description: "Álbum removido com sucesso"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de sucesso"
                example:
                  message: "Álbum removido com sucesso"
        "404":
          description: "Álbum não encontrado"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Álbum não encontrado"
        "400":
          description: "ID inválido"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "ID inválido"
        "500":
          description: "Erro interno do servidor"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: "Mensagem de erro"
                example:
                  message: "Erro interno do servidor"
  

# aqui eu crio componentes que serão reutilizados
components:
  schemas:
    UserRegister:
      type: object
      required:
        - email
        - password
        - name
      properties:
        email:
          type: string
          description: "Email do usuário"

        password:
          type: string
          description: "Senha do usuário"
        name:
          type: string
          description: "Nome do usuário"

    UserLogin:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          description: "Email do usuário"

        password:
          type: string
          description: "Senha do usuário"
      example :
            email: "admin@example.com"
            password: "admin123"

    ArtistCreate:
      type: object
      required:
        - name
        - genre
        - bio
      properties:
        name:
          type: string
          description: "Nome do artista"
        genre:
          type: string
          description: "Gênero musical do artista"
        bio:
          type: string
          description: "Biografia do artista"
        imageURL:
          type: string
          description: "URL da imagem do artista"
        imageBase64:
          type: string
          description: "Imagem do artista em base64 (opcional)"
      example:
        name: "Artista Exemplo"
        genre: "Pop"
        bio: "Biografia do artista exemplo."
        imageURL: "https://example.com/image.jpg"
        imageBase64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."

    SongsCreate:
      type: object
      required:
        - title
        - duration
        - artistName
      properties:
        title:
          type: string
          description: "titulo da música"
        duration:
          type: string
          description: "tempo de duração das musicas"
        artistName:
          type: string
          description: "nome do artista"
        imageURL:
          type: string
          description: "URL da imagem do artista"
        imageBase64:
          type: string
          description: "Imagem do artista em base64 (opcional)"
      example:
        title: "Música Exemplo"
        duration: "3:45"
        artistName: "Artista Exemplo"
        imageURL: "https://example.com/image.jpg"
        imageBase64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."

    AlbumCreate:
      type: object
      required:
        - title
        - artistName
        - releaseDate
      properties:
        title:
          type: string
          description: "Título do álbum"
        artistName:
          type: string
          description: "Nome do artista"
        releaseDate:
          type: string
          format: date-time
          description: "Data de lançamento do álbum"
        imageURL:
          type: string
          description: "URL da imagem do álbum"
        imageBase64:
          type: string
          description: "Imagem do álbum em base64 (opcional)"
      example:
        title: "Álbum Exemplo"
        artistName: "Artista Exemplo"
        releaseDate: "2023-10-01T00:00:00Z"
        imageURL: "https://example.com/album.jpg"
        imageBase64: "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUA..."
  # aqui eu defino os esquemas de segurança
  securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT

    